<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-1SAS5MA" failures="1" tests="1" name="TCS_IndGoldEssen_0001" time="2.606" errors="0" timestamp="21 Jun 2020 10:56:18 GMT">
  <testcase classname="testRunner.TestExecutionSuite" name="executionSuite" time="2.21">
    <failure type="com.codoid.products.exception.FilloException" message="Unable to connect workbook - C:\Users\Nishant\Desktop\TCS-framework\FrameWork\GSTNTestData\GST_Return\TestDataSuite\0002_TestDataSuite.xlsx">
      <![CDATA[com.codoid.products.exception.FilloException: Unable to connect workbook - C:\Users\Nishant\Desktop\TCS-framework\FrameWork\GSTNTestData\GST_Return\TestDataSuite\0002_TestDataSuite.xlsx
at com.codoid.products.fillo.Fillo.getWorkbook(Fillo.java:67)
at com.codoid.products.fillo.Fillo.getConnection(Fillo.java:41)
at testRunner.TestExecutionSuite.executionSuite(TestExecutionSuite.java:59)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- executionSuite -->
</testsuite> <!-- TCS_IndGoldEssen_0001 -->
